//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClonestoneFSEntities : DbContext
    {
        public ClonestoneFSEntities()
            : base("name=ClonestoneFSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
        public virtual DbSet<Deckcard> Deckcards { get; set; }
        public virtual DbSet<Deck> Decks { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Pack> Packs { get; set; }
        public virtual DbSet<Person> AllPeople { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<vEditor> vEditor { get; set; }
    }
}
