//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public int ID { get; set; }
        public Nullable<int> CollectionNumberOfCards { get; set; }
        public Nullable<int> ID_Person { get; set; }
        public Nullable<int> ID_Order { get; set; }
        public Nullable<int> ID_DeckCard { get; set; }
        public int ID_Card { get; set; }
    
        public virtual DeckCard Deck { get; set; }
        public virtual Order AllOrders { get; set; }
        public virtual Person Person { get; set; }
        public virtual Card Card { get; set; }
    }
}
