//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEditor
    {
        public int idedit { get; set; }
        public int ideditfile { get; set; }
        public int idperson { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public byte[] editfile { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
    }
}
